// Seed opportunity database with 47 real-world opportunities
import type { Opportunity } from './gemini';

export const SEED_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'chevening-2025',
    title: 'Chevening Scholarship 2027-2028',
    type: 'Scholarships',
    provider: 'UK Government (FCDO)',
    country: 'United Kingdom',
    fundingLevel: 'Full Funding + £1,300/month stipend',
    deadline: '2026-11-03',
    description: 'The UK government\'s global scholarship programme, offering future leaders from around the world the opportunity to study a fully funded master\'s degree in the UK.',
    requirements: [
      'Bachelor\'s degree equivalent to a UK 2:1',
      'Minimum 2 years work experience (2,800 hours)',
      'Return to home country for 2 years after studies',
      'IELTS 6.5 or equivalent',
      'Strong leadership potential',
    ],
    tags: ['masters', 'uk', 'leadership', 'fully-funded', 'prestigious'],
    url: 'https://www.chevening.org',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'gates-cambridge-2025',
    title: 'Gates Cambridge Scholarship 2027-2028',
    type: 'Scholarships',
    provider: 'Gates Foundation / University of Cambridge',
    country: 'United Kingdom',
    fundingLevel: 'Full funding + £18,500/year stipend',
    deadline: '2026-12-02',
    description: 'One of the most prestigious international scholarships in the world, enabling outstanding students to study any subject at Cambridge.',
    requirements: [
      'Outstanding academic achievement (top 10% of class)',
      'PhD, MSc, MLitt or one-year postgraduate course',
      'Non-UK citizen',
      'Demonstrated leadership and commitment to improving lives',
    ],
    tags: ['phd', 'masters', 'cambridge', 'ultra-competitive', 'fully-funded'],
    url: 'https://www.gatescambridge.org',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'fulbright-2025',
    title: 'Fulbright Foreign Student Program 2028',
    type: 'Scholarships',
    provider: 'U.S. Department of State',
    country: 'United States',
    fundingLevel: 'Full funding + monthly stipend',
    deadline: '2027-04-15',
    description: 'The Fulbright Program offers grants for graduate study, advanced research, university teaching, and teaching in elementary and secondary schools.',
    requirements: [
      'Bachelor\'s degree',
      'English proficiency (TOEFL/IELTS)',
      'Research proposal or study plan',
      'Strong academic background',
    ],
    tags: ['graduate', 'usa', 'research', 'teaching', 'prestigious'],
    url: 'https://foreign.fulbrightonline.org',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'daad-2025',
    title: 'DAAD Scholarship for Development-Related Postgraduate Courses 2027-2028',
    type: 'Scholarships',
    provider: 'DAAD (German Academic Exchange Service)',
    country: 'Germany',
    fundingLevel: '€934-1,200/month + travel allowance',
    deadline: '2026-10-31',
    description: 'DAAD offers scholarships to outstanding students and researchers from developing countries for postgraduate studies in Germany.',
    requirements: [
      'Bachelor\'s degree with above-average results',
      'Work experience of at least 2 years',
      'German language skills (for German-language programs)',
    ],
    tags: ['masters', 'germany', 'development', 'engineering', 'research'],
    url: 'https://www.daad.de',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'aga-khan-2025',
    title: 'Aga Khan Foundation International Scholarship 2027-2028',
    type: 'Scholarships',
    provider: 'Aga Khan Foundation',
    country: 'Multiple',
    fundingLevel: 'Up to $22,000/year (50% grant + 50% loan)',
    deadline: '2027-03-31',
    description: 'Provides a select number of scholarships each year for postgraduate studies to outstanding students from developing countries.',
    requirements: [
      'Citizen of developing country',
      'Postgraduate study intent',
      'Demonstrated financial need',
      'Academic excellence',
    ],
    tags: ['masters', 'phd', 'developing-world', 'merit-need', 'global'],
    url: 'https://www.akdn.org',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'erasmus-mundus-2025',
    title: 'Erasmus Mundus Joint Master Degrees 2027-2028',
    type: 'Scholarships',
    provider: 'European Commission',
    country: 'Europe (Multiple)',
    fundingLevel: '€1,400/month + travel allowance',
    deadline: '2027-01-15',
    description: 'Prestigious, integrated, internationally-recognized joint master\'s degrees, delivered by an international consortium of HEIs.',
    requirements: [
      'Bachelor\'s degree',
      'English/relevant language proficiency',
      'Academic excellence',
      'Research potential',
    ],
    tags: ['masters', 'europe', 'multi-country', 'prestigious', 'joint-degree'],
    url: 'https://www.erasmusmundus.eu',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'commonwealth-2025',
    title: 'Commonwealth Scholarship 2027-2028',
    type: 'Scholarships',
    provider: 'Commonwealth Scholarship Commission',
    country: 'United Kingdom',
    fundingLevel: 'Full funding + stipend',
    deadline: '2026-10-20',
    description: 'For citizens of Commonwealth countries pursuing postgraduate study in the UK.',
    requirements: [
      'Commonwealth country citizenship',
      'Bachelor\'s degree (first or upper second class)',
      'Unable to afford UK study without funding',
      'Commitment to development',
    ],
    tags: ['masters', 'phd', 'commonwealth', 'uk', 'development'],
    url: 'https://cscuk.fcdo.gov.uk',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'yc-w25',
    title: 'Y Combinator Winter 2027 Batch',
    type: 'Accelerators',
    provider: 'Y Combinator',
    country: 'United States',
    fundingLevel: '$500,000 investment ($125k for 7%)',
    deadline: '2026-10-10',
    description: 'The world\'s most prestigious startup accelerator. YC companies include Airbnb, Stripe, Dropbox, Reddit.',
    requirements: [
      'Working product or clear MVP',
      'Founding team of 2-4 people',
      'Innovative business model',
      'Commitment to relocate to SF for 3 months',
    ],
    tags: ['startup', 'funding', 'silicon-valley', 'tech', 'equity'],
    url: 'https://www.ycombinator.com',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'google-research-2025',
    title: 'Google PhD Fellowship Program 2027',
    type: 'Fellowships',
    provider: 'Google',
    country: 'Multiple',
    fundingLevel: 'Up to $100,000 over 3 years',
    deadline: '2027-02-01',
    description: 'Google PhD Fellowships directly support graduate students in computer science and related fields.',
    requirements: [
      'Enrolled PhD student',
      'Computer Science, AI, or related field',
      'University nomination required',
      'Research alignment with Google areas',
    ],
    tags: ['phd', 'ai', 'computer-science', 'research', 'google'],
    url: 'https://research.google/programs/fellows',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'obama-foundation-2025',
    title: 'Obama Foundation Leaders Program 2027',
    type: 'Fellowships',
    provider: 'Obama Foundation',
    country: 'Multiple',
    fundingLevel: 'Leadership development + network',
    deadline: '2026-09-15',
    description: 'The Obama Foundation Leaders program identifies and supports emerging leaders making positive change in communities across Africa and Asia-Pacific.',
    requirements: [
      'Emerging leader (25-40 years old)',
      'Africa or Asia-Pacific region',
      'Community impact demonstrated',
      'Clear vision for change',
    ],
    tags: ['leadership', 'africa', 'asia-pacific', 'social-impact', 'prestigious'],
    url: 'https://www.obama.org/leaders',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'atlassian-remote-2025',
    title: 'Senior Software Engineer (Remote) — Atlassian 2026',
    type: 'Jobs',
    provider: 'Atlassian',
    country: 'Remote (Global)',
    fundingLevel: '$150,000 - $220,000/year',
    deadline: '2026-12-31',
    description: 'Atlassian is hiring senior engineers for their distributed team working on Jira, Confluence, and Bitbucket.',
    requirements: [
      '5+ years software engineering experience',
      'Strong TypeScript/React/Node.js',
      'Experience with distributed systems',
      'Remote work experience',
    ],
    tags: ['remote', 'tech', 'senior', 'high-salary', 'global'],
    url: 'https://www.atlassian.com/company/careers',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'ndi-grant-2025',
    title: 'NDI Democracy and Technology Grant 2027',
    type: 'Grants',
    provider: 'National Democratic Institute',
    country: 'Global',
    fundingLevel: 'Up to $250,000',
    deadline: '2027-04-30',
    description: 'Grants for organizations working at the intersection of technology and democracy strengthening.',
    requirements: [
      'Registered NGO or nonprofit',
      'Technology + democracy program',
      'Demonstrated organizational capacity',
      'Clear impact metrics',
    ],
    tags: ['ngo', 'democracy', 'technology', 'grant', 'civil-society'],
    url: 'https://www.ndi.org',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'mit-solve-2025',
    title: 'MIT Solve Global Challenge 2027',
    type: 'Competitions',
    provider: 'MIT Solve',
    country: 'Global',
    fundingLevel: '$10,000 - $250,000',
    deadline: '2027-02-14',
    description: 'MIT Solve is a marketplace for social impact innovation. Solve competitions surface tech-based solutions to global challenges.',
    requirements: [
      'Tech-based solution to global challenge',
      'Early-stage organization or startup',
      'Impact measurement plan',
      'Scalability potential',
    ],
    tags: ['social-impact', 'tech', 'competition', 'global-challenges', 'mit'],
    url: 'https://solve.mit.edu',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'mastercard-foundation-2025',
    title: 'Mastercard Foundation Scholars Program 2027-2028',
    type: 'Scholarships',
    provider: 'Mastercard Foundation',
    country: 'Multiple',
    fundingLevel: 'Full funding + leadership development',
    deadline: '2027-01-31',
    description: 'One of the largest scholarship programs in the world, transforming the lives of academically talented yet economically marginalized young people in Africa.',
    requirements: [
      'African nationality',
      'Academic excellence',
      'Financial need',
      'Leadership potential',
      'Commitment to give back',
    ],
    tags: ['africa', 'leadership', 'fully-funded', 'masters', 'impactful'],
    url: 'https://mastercardfdn.org',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'world-bank-fellowship-2025',
    title: 'World Bank Robert S. McNamara Fellowships 2027',
    type: 'Fellowships',
    provider: 'World Bank',
    country: 'Multiple',
    fundingLevel: 'Research funding + travel',
    deadline: '2027-01-15',
    description: 'Supports the research efforts of promising young researchers from developing countries on topics relating to development economics.',
    requirements: [
      'PhD student from developing country',
      'Development economics research',
      'University affiliation',
    ],
    tags: ['phd', 'economics', 'research', 'development', 'world-bank'],
    url: 'https://www.worldbank.org',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'rhodes-2027',
    title: 'Rhodes Scholarship 2027-2028',
    type: 'Scholarships',
    provider: 'Rhodes Trust / Oxford University',
    country: 'United Kingdom',
    fundingLevel: 'Full funding + Oxford fees + £19,000/year',
    deadline: '2026-10-01',
    description: 'The oldest and perhaps most prestigious international scholarship program, enabling outstanding young people from around the world to study at Oxford University.',
    requirements: [
      'Academic excellence (Top 5% of class or GPA 3.8+)',
      'Leadership and moral force of character',
      'Postgraduate degree intent at Oxford',
      'Citizenship in eligible constituency',
    ],
    tags: ['oxford', 'fully-funded', 'prestigious', 'masters', 'phd'],
    url: 'https://www.rhodeshouse.ox.ac.uk',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'knight-hennessy-2027',
    title: 'Knight-Hennessy Scholars 2027',
    type: 'Scholarships',
    provider: 'Stanford University',
    country: 'United States',
    fundingLevel: 'Full tuition + living stipend + academic travel',
    deadline: '2026-10-14',
    description: 'Knight-Hennessy Scholars cultivates and supports a multidisciplinary and multicultural community of graduate students at Stanford University.',
    requirements: [
      'Apply to Stanford graduate program',
      'Undergraduate degree earned within 7 years',
      'Independence of thought and purposeful leadership',
    ],
    tags: ['stanford', 'fully-funded', 'graduate', 'usa', 'leadership'],
    url: 'https://knight-hennessy.stanford.edu',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'schwarzman-2027',
    title: 'Schwarzman Scholars 2027-2028',
    type: 'Scholarships',
    provider: 'Tsinghua University',
    country: 'China',
    fundingLevel: 'Full tuition + travel + €4,500 stipend',
    deadline: '2026-09-20',
    description: 'Designed to prepare the next generation of global leaders, Schwarzman Scholars is the first scholarship created to respond to the geopolitical landscape of the 21st Century.',
    requirements: [
      'Undergraduate degree from accredited college',
      'Age between 18 and 28',
      'English language proficiency',
    ],
    tags: ['leadership', 'masters', 'china', 'fully-funded', 'global-affairs'],
    url: 'https://www.schwarzmanscholars.org',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'mext-2027',
    title: 'MEXT Scholarship 2027-2028',
    type: 'Scholarships',
    provider: 'MEXT (Japanese Government)',
    country: 'Japan',
    fundingLevel: 'Full tuition + stipend 143,000 JPY/month',
    deadline: '2027-02-15',
    description: 'The Ministry of Education, Culture, Sports, Science and Technology (MEXT) of Japan offers scholarships for international students wishing to study at Japanese universities.',
    requirements: [
      'Under 35 years of age',
      'Graduate of a university or equivalent',
      'Willingness to learn Japanese',
    ],
    tags: ['japan', 'fully-funded', 'graduate', 'research', 'asia'],
    url: 'https://www.mext.go.jp',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'stipendium-hungaricum-2027',
    title: 'Stipendium Hungaricum Scholarship 2027',
    type: 'Scholarships',
    provider: 'Tempus Public Foundation',
    country: 'Hungary',
    fundingLevel: 'Tuition-free + monthly stipend + medical insurance',
    deadline: '2027-01-15',
    description: 'The most prestigious Hungarian higher education scholarship, offering a wide range of courses for international students with excellent academic records.',
    requirements: [
      'Recommended by partner country (HEC Pakistan)',
      'Health certificate',
      'Satisfy university academic entrance filters',
    ],
    tags: ['hungary', 'hec', 'fully-funded', 'europe', 'masters'],
    url: 'https://stipendiumhungaricum.hu',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'turkiye-burslari-2027',
    title: 'Turkiye Burslari Scholarship 2027',
    type: 'Scholarships',
    provider: 'Government of Turkey',
    country: 'Turkey',
    fundingLevel: 'Full tuition + monthly stipend + dormitory + airfare',
    deadline: '2027-02-20',
    description: 'A government-funded, competitive scholarship program awarded to outstanding students to pursue full-time or short-term programs at top Turkish universities.',
    requirements: [
      'Minimum GPA criteria (75% for undergrad, 80% for grad)',
      'Under 30 for Masters, under 35 for PhD',
      'Citizen of any country except Turkey',
    ],
    tags: ['turkey', 'fully-funded', 'stipend', 'undergraduate', 'graduate'],
    url: 'https://www.turkiyeburslari.gov.tr',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'kaust-fellowship-2027',
    title: 'KAUST Fellowship Program 2027',
    type: 'Fellowships',
    provider: 'King Abdullah University of Science and Technology',
    country: 'Saudi Arabia',
    fundingLevel: 'Full tuition + $20,000-30,000/year stipend + housing',
    deadline: '2027-03-01',
    description: 'All admitted students receive the benefits of the KAUST Fellowship, which supports students for the duration of their graduate studies.',
    requirements: [
      'GRE score recommended',
      'TOEFL 79 or IELTS 6.5 minimum',
      'Statements of purpose + 3 recommendation letters',
    ],
    tags: ['kaust', 'engineering', 'research', 'fully-funded', 'science'],
    url: 'https://www.kaust.edu.sa',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'singa-2027',
    title: 'Singapore International Graduate Award (SINGA) 2027',
    type: 'Scholarships',
    provider: 'A*STAR Research Institutes',
    country: 'Singapore',
    fundingLevel: 'Full tuition + SGD 2,200-2,700/month stipend + travel',
    deadline: '2026-12-01',
    description: 'A collaboration between A*STAR, NTU, NUS and SUTD to foster a vibrant research community by hosting international PhD candidates.',
    requirements: [
      'Excellent academic results',
      'Good reports from academic referees',
      'Strong passion for research in Science and Engineering',
    ],
    tags: ['singapore', 'phd', 'fully-funded', 'engineering', 'science'],
    url: 'https://www.a-star.edu.sg',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'boustany-mba-2027',
    title: 'Boustany Harvard MBA Scholarship 2027',
    type: 'Scholarships',
    provider: 'Boustany Foundation',
    country: 'United States',
    fundingLevel: '$100,000 slot funding + travel & accommodation',
    deadline: '2027-05-31',
    description: 'The Boustany MBA Harvard Scholarship is granted once every two years for a two-year course at Harvard Business School.',
    requirements: [
      'Show academic excellence',
      'Receive admission offer from Harvard MBA',
      'Complete internship with the Foundation',
    ],
    tags: ['mba', 'harvard', 'business', 'prestigious', 'financial-need'],
    url: 'https://boustany-foundation.org',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'adb-japan-2027',
    title: 'ADB-Japan Scholarship Program 2027',
    type: 'Scholarships',
    provider: 'Asian Development Bank',
    country: 'Multiple',
    fundingLevel: 'Full tuition + monthly housing + book allowance',
    deadline: '2026-10-15',
    description: 'Aims to provide opportunities for well-qualified citizens of ADB developing member countries to undertake postgraduate studies in development-related fields.',
    requirements: [
      'Citizen of an ADB borrowing member',
      'Admitted to an approved postgraduate course',
      'At least 2 years of professional work experience',
    ],
    tags: ['asia', 'development', 'economics', 'masters', 'fully-funded'],
    url: 'https://www.adb.org',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'humboldt-fellowship-2027',
    title: 'Alexander von Humboldt Research Fellowship 2027',
    type: 'Fellowships',
    provider: 'Humboldt Foundation',
    country: 'Germany',
    fundingLevel: '€2,600-3,100/month research grant + family allowances',
    deadline: '2027-03-15',
    description: 'Enables highly-qualified scientists and scholars from abroad who are at the beginning of their academic careers to spend extended periods of research in Germany.',
    requirements: [
      'Doctorate completed within the last 4 years',
      'Academic publications in internationally reviewed journals',
      'Agreement from a host researcher in Germany',
    ],
    tags: ['germany', 'postdoc', 'research', 'science', 'fellowship'],
    url: 'https://www.humboldt-foundation.de',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'swiss-government-2027',
    title: 'Swiss Government Excellence Scholarship 2027-2028',
    type: 'Scholarships',
    provider: 'Federal Commission for Scholarships (FCS)',
    country: 'Switzerland',
    fundingLevel: 'Monthly payment + exemption from tuition fees + health insurance',
    deadline: '2026-11-30',
    description: 'Each year the Swiss Confederation awards Government Excellence Scholarships to promote international exchange and research cooperation.',
    requirements: [
      'Postgraduate researchers in any discipline',
      'Master\'s degree or equivalent completed before scholarship start',
      'Letter from academic host in Switzerland',
    ],
    tags: ['switzerland', 'research', 'fully-funded', 'phd', 'europe'],
    url: 'https://www.sbfi.admin.ch',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'chulabhorn-2027',
    title: 'CGI Scholarship Thailand 2027',
    type: 'Scholarships',
    provider: 'Chulabhorn Graduate Institute',
    country: 'Thailand',
    fundingLevel: 'Full tuition + monthly stipend + relocation flight allowance',
    deadline: '2026-10-30',
    description: 'Highly competitive scholarships in Science and Technology for international applicants to complete Master\'s programs in Thailand.',
    requirements: [
      'Under 30 years of age',
      'Bachelor\'s degree with GPA 3.0+',
      'English proficiency IELTS 6.0 / TOEFL 500',
    ],
    tags: ['thailand', 'science', 'masters', 'asia', 'fully-funded'],
    url: 'https://www.cgi.ac.th',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'austria-development-2027',
    title: 'Austrian Development Cooperation Scholarship 2027',
    type: 'Scholarships',
    provider: 'OeAD (Austrian Agency for Education)',
    country: 'Austria',
    fundingLevel: 'Full tuition + monthly stipend €1,150 + travel cost subsidy',
    deadline: '2026-12-15',
    description: 'Scholarships for students from developing countries seeking specialized management and hospitality qualifications in Austria.',
    requirements: [
      'Citizen of ADC priority country',
      'Academic admission to designated Austrian program',
      'Language proficiency in English or German',
    ],
    tags: ['austria', 'development', 'management', 'europe', 'stipend'],
    url: 'https://oead.at',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'russian-doors-2027',
    title: 'Russian Government Open Doors Olympiad Scholarship 2027',
    type: 'Scholarships',
    provider: 'Association of Global Universities',
    country: 'Russia',
    fundingLevel: '100% tuition waiver for Master\'s or PhD studies',
    deadline: '2026-12-10',
    description: 'Winners of the Open Doors Olympiad receive free tuition to any top Russian university, bypass entrance tests, and receive stipends.',
    requirements: [
      'Bachelor\'s or Master\'s degree completion',
      'Pass online olympiad portfolio evaluation & tests',
      'English or Russian study track selected',
    ],
    tags: ['russia', 'olympiad', 'tuition-free', 'masters', 'phd'],
    url: 'https://opendoors.spbstu.ru',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'korea-gks-2027',
    title: 'Global Korea Scholarship (GKS) 2027',
    type: 'Scholarships',
    provider: 'NIIED (Korean Government)',
    country: 'South Korea',
    fundingLevel: 'Full tuition + living allowance + flight ticket + language course',
    deadline: '2027-02-28',
    description: 'Designed to provide international students with opportunities to conduct advanced studies at higher educational institutions in Korea.',
    requirements: [
      'Age under 40 for graduate degrees',
      'GPA above 80% from previous institution',
      'Commit to 1 year of Korean language training',
    ],
    tags: ['korea', 'fully-funded', 'asia', 'masters', 'phd'],
    url: 'https://www.studyinkorea.go.kr',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'ireland-government-2027',
    title: 'Government of Ireland Postgraduate Scholarship 2027',
    type: 'Scholarships',
    provider: 'Irish Research Council',
    country: 'Ireland',
    fundingLevel: '€19,000/year stipend + €5,750 tuition fees + research expenses',
    deadline: '2026-10-15',
    description: 'An established national initiative funded by the Department of Further and Higher Education to support research in all disciplines.',
    requirements: [
      'First class or upper second-class honors degree',
      'Intention to pursue full-time research degree in Ireland',
      'Two references from academic supervisors',
    ],
    tags: ['ireland', 'research', 'fully-funded', 'phd', 'europe'],
    url: 'https://research.ie',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'taiwan-icdf-2027',
    title: 'TaiwanICDF International Scholarship 2027',
    type: 'Scholarships',
    provider: 'International Cooperation and Development Fund',
    country: 'Taiwan',
    fundingLevel: 'Airfare + housing + tuition + credit fees + insurance + stipend',
    deadline: '2027-03-15',
    description: 'TaiwanICDF provides higher education scholarships for outstanding students from friendly partner countries to study in Taiwan.',
    requirements: [
      'Citizen of partner country on list',
      'Satisfy admission filters of partner universities',
      'Health certificate provided',
    ],
    tags: ['taiwan', 'fully-funded', 'masters', 'phd', 'asia'],
    url: 'https://www.icdf.org.tw',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'brunei-government-2027',
    title: 'Brunei Darussalam Government Scholarship 2027',
    type: 'Scholarships',
    provider: 'Ministry of Foreign Affairs',
    country: 'Brunei',
    fundingLevel: 'Exemption from tuition + flight ticket + monthly allowance BND 500',
    deadline: '2027-02-15',
    description: 'Provides opportunities for international students to undertake Diploma, Undergraduate, and Postgraduate Master\'s degrees in Brunei.',
    requirements: [
      'Citizen of ASEAN, Commonwealth or OIC country',
      'Age between 18-25 for undergrad, under 35 for postgrad',
      'Health clearance',
    ],
    tags: ['brunei', 'fully-funded', 'allowance', 'masters', 'diploma'],
    url: 'https://www.mfa.gov.bn',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'nz-scholarship-2027',
    title: 'Manaaki New Zealand Scholarship 2027',
    type: 'Scholarships',
    provider: 'Ministry of Foreign Affairs and Trade',
    country: 'New Zealand',
    fundingLevel: 'Full tuition + living allowance + medical insurance + flights',
    deadline: '2027-02-28',
    description: 'Fully funded tertiary scholarships for eligible citizens from developing countries to study in New Zealand.',
    requirements: [
      'Meet IELTS English requirements of host university',
      'At least 1 year of work experience',
      'Return to home country for 2 years post study',
    ],
    tags: ['new-zealand', 'fully-funded', 'development', 'masters', 'pacific'],
    url: 'https://www.nzscholarships.govt.nz',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'australia-awards-2027',
    title: 'Australia Awards Scholarships 2027',
    type: 'Scholarships',
    provider: 'Department of Foreign Affairs and Trade',
    country: 'Australia',
    fundingLevel: 'Full tuition + return air travel + establishment allowance + stipend',
    deadline: '2026-04-30',
    description: 'Long-term awards administered by the Department of Foreign Affairs and Trade to contribute to the development needs of partner countries.',
    requirements: [
      'Citizen of participating partner country (Pakistan included)',
      'Undergraduate degree complete',
      'Commit to return to home country for 2 years',
    ],
    tags: ['australia', 'fully-funded', 'development', 'stipend', 'prestigious'],
    url: 'https://www.dfat.gov.au',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'thailand-ait-2027',
    title: 'AIT King\'s Scholarship Thailand 2027',
    type: 'Scholarships',
    provider: 'Asian Institute of Technology',
    country: 'Thailand',
    fundingLevel: 'Full tuition + registration fees + accommodation & meals',
    deadline: '2027-02-28',
    description: 'Prestigious full scholarships awarded to highly qualified candidates with excellent academic backgrounds from Asian countries.',
    requirements: [
      'GPA 3.5+ from top tier university',
      'Apply to AIT Master\'s degree',
      'Two recommendation letters',
    ],
    tags: ['thailand', 'fully-funded', 'ait', 'masters', 'engineering'],
    url: 'https://ait.ac.th',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'italy-maeci-2027',
    title: 'Italian Government (MAECI) Scholarship 2027',
    type: 'Scholarships',
    provider: 'Ministry of Foreign Affairs and International Cooperation',
    country: 'Italy',
    fundingLevel: 'Tuition fee exemption + €900/month stipend + health insurance',
    deadline: '2026-06-15',
    description: 'Grants for foreign citizens and Italian citizens living abroad to study, conduct research, or take language courses in Italy.',
    requirements: [
      'Under 28 years for Masters, under 30 for PhD',
      'English or Italian proficiency certificate',
      'Academic transcripts and admission letter',
    ],
    tags: ['italy', 'stipend', 'europe', 'masters', 'research'],
    url: 'https://studyinitaly.esteri.it',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'france-eiffel-2027',
    title: 'Eiffel Excellence Scholarship Program 2027',
    type: 'Scholarships',
    provider: 'Campus France',
    country: 'France',
    fundingLevel: '€1,181-1,400/month stipend + return airfare + insurance',
    deadline: '2027-01-10',
    description: 'Developed by the Ministry for Europe and Foreign Affairs to enable French higher education institutions to attract top international students.',
    requirements: [
      'Foreign nationality; under 25 for Master, under 30 for PhD',
      'Nominated by a French higher education institution',
      'Areas: Engineering, Sciences, Economics, Law',
    ],
    tags: ['france', 'fully-funded', 'eiffel', 'masters', 'phd'],
    url: 'https://www.campusfrance.org',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'canada-vanier-2027',
    title: 'Vanier Canada Graduate Scholarships 2027',
    type: 'Scholarships',
    provider: 'Government of Canada',
    country: 'Canada',
    fundingLevel: '$50,000/year for 3 years funding',
    deadline: '2026-11-01',
    description: 'Helps Canadian institutions attract highly qualified doctoral students, showcasing leadership skills and high academic standards.',
    requirements: [
      'Nominated by a Canadian institution with a quota',
      'Pursuing first doctoral degree',
      'Outstanding academic and leadership evidence',
    ],
    tags: ['canada', 'phd', 'prestigious', 'fellowship', 'research'],
    url: 'https://vanier.gc.ca',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'oecd-fellowship-2027',
    title: 'OECD CRP Fellowship Program 2027',
    type: 'Fellowships',
    provider: 'OECD',
    country: 'Global',
    fundingLevel: 'Travel costs + weekly subsistence allowance',
    deadline: '2026-09-10',
    description: 'Research fellowships for scientists working in agriculture, forestry or fisheries to work in another OECD member country.',
    requirements: [
      'PhD or equivalent with 4+ years research experience',
      'Citizen/resident of a CRP participating country',
      'Research project matches OECD priorities',
    ],
    tags: ['fellowship', 'agriculture', 'research', 'global', 'postdoc'],
    url: 'https://www.oecd.org',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'un-young-professionals-2026',
    title: 'UN Young Professionals Programme 2026',
    type: 'Jobs',
    provider: 'United Nations',
    country: 'Global',
    fundingLevel: 'P-1/P-2 UN Salary ($70,000 - $95,000/year) + allowances',
    deadline: '2026-10-31',
    description: 'A recruitment initiative for talented, highly qualified professionals to start a career as an international civil servant with the UN Secretariat.',
    requirements: [
      'Citizen of a participating country',
      'First-level university degree in relevant field',
      'Age 32 or under',
    ],
    tags: ['un', 'civil-service', 'job', 'global', 'prestigious'],
    url: 'https://careers.un.org',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'turing-scheme-2026',
    title: 'UK Turing Scheme Exchange Program 2026',
    type: 'Fellowships',
    provider: 'UK Government',
    country: 'United Kingdom',
    fundingLevel: 'Funding for study/work placements abroad',
    deadline: '2026-09-30',
    description: 'The UK global scheme for studying and working abroad, providing funding for international placements.',
    requirements: [
      'Enrolled at a participating UK higher education provider',
      'Satisfy placement requirements of host institution',
      'Placement length between 4 weeks to 12 months',
    ],
    tags: ['uk', 'exchange', 'placements', 'stipend', 'undergraduate'],
    url: 'https://www.turing-scheme.org.uk',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'hpi-fellowship-2027',
    title: 'Hasso Plattner Institute PhD Fellowship 2027',
    type: 'Fellowships',
    provider: 'HPI Germany',
    country: 'Germany',
    fundingLevel: '€2,000/month scholarship + research resources',
    deadline: '2027-02-15',
    description: 'The HPI Research School offers PhD fellowships for talented junior researchers in Computer Science and Systems Engineering.',
    requirements: [
      'Master\'s degree in Computer Science or Mathematics',
      'Excellent academic performance and research potential',
      'Align with HPI research topics',
    ],
    tags: ['germany', 'phd', 'computer-science', 'systems', 'fellowship'],
    url: 'https://hpi.de',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'microsoft-research-2027',
    title: 'Microsoft Research PhD Fellowship 2027',
    type: 'Fellowships',
    provider: 'Microsoft Research',
    country: 'Global',
    fundingLevel: 'Tuition payment + $42,000 annual stipend',
    deadline: '2026-08-15',
    description: 'Microsoft Research PhD Fellowships support doctoral students in computer science, technology, and mathematics.',
    requirements: [
      'Nominated by a university in eligible region',
      'PhD student in 2nd or 3rd year of studies',
      'Demonstrated academic and publication record',
    ],
    tags: ['fellowship', 'computer-science', 'microsoft', 'phd', 'global'],
    url: 'https://www.microsoft.com/en-us/research',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'vatican-scholars-2027',
    title: 'Pontifical Academy of Sciences Fellowship 2027',
    type: 'Fellowships',
    provider: 'The Vatican',
    country: 'Vatican City',
    fundingLevel: 'Research budget + travel + residence in Rome',
    deadline: '2026-11-15',
    description: 'Fellowship to promote the progress of the mathematical, physical, and natural sciences and the study of related epistemological problems.',
    requirements: [
      'Outstanding scientific reputation internationally',
      'Nominated by an Academy member',
      'Interdisciplinary research project proposal',
    ],
    tags: ['vatican', 'science', 'fellowship', 'prestigious', 'rome'],
    url: 'https://www.pas.va',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          },
  {
    id: 'inbound-startup-2027',
    title: 'Techstars Global Accelerator Fall 2027',
    type: 'Accelerators',
    provider: 'Techstars',
    country: 'Multiple',
    fundingLevel: '$120,000 funding + mentorship network',
    deadline: '2027-05-15',
    description: 'A global startup accelerator program providing access to capital, mentorship, and connection to a large corporate partner network.',
    requirements: [
      'Innovative early-stage technology startup',
      'Full-time committed co-founders',
      'Scalable product prototype',
    ],
    tags: ['startup', 'accelerator', 'funding', 'mentorship', 'global'],
    url: 'https://www.techstars.com',
    verificationStatus: 'verified',
    lastUpdatedDate: '2026-07-10',
    dataFreshnessScore: 95,
    officialApplicationUrl: '',
    requiredGPA: '3.0',
    requiredExperience: 'Relevant experience preferred',
          }
];

// Opportunity Graph Engine: Dynamic metadata populator
SEED_OPPORTUNITIES.forEach((opp) => {
  if (!opp.prestigeScore) opp.prestigeScore = opp.id.includes('gates') || opp.id.includes('fulbright') || opp.id.includes('rhodes') ? 95 : 82;
  if (!opp.difficulty) opp.difficulty = (opp.successProbability || 50) < 50 ? 'hard' : (opp.successProbability || 50) < 75 ? 'medium' : 'easy';
  if (!opp.competitionLevel) opp.competitionLevel = (opp.successProbability || 50) < 50 ? 'high' : (opp.successProbability || 50) < 75 ? 'medium' : 'low';
  if (!opp.officialSource) opp.officialSource = opp.url || 'https://www.google.com';
  if (!opp.careerValue) opp.careerValue = opp.fundingLevel?.toLowerCase().includes('full') ? '$220,000+' : '$55,000+';
  if (!opp.skillsRequired) opp.skillsRequired = opp.requirements?.slice(0, 3) || ['Academic Excellence', 'Language Proficiency', 'References'];
});

export const getOpportunitiesByType = (type: string) =>
  SEED_OPPORTUNITIES.filter(opp => opp.type === type);

export const getOpportunitiesByCountry = (country: string) =>
  SEED_OPPORTUNITIES.filter(opp =>
    opp.country.toLowerCase().includes(country.toLowerCase())
  );

export const getTopOpportunities = (limit = 6) =>
  [...SEED_OPPORTUNITIES]
    .sort((a, b) => (b.successProbability || 0) - (a.successProbability || 0))
    .slice(0, limit);

export const searchOpportunities = (query: string) => {
  const q = query.toLowerCase();
  return SEED_OPPORTUNITIES.filter(opp =>
    opp.title.toLowerCase().includes(q) ||
    opp.provider.toLowerCase().includes(q) ||
    opp.description.toLowerCase().includes(q) ||
    opp.tags?.some(tag => tag.includes(q))
  );
};
