// ============================================================
//  Central SEO configuration & helpers
// ============================================================
// Single source of truth for the canonical site URL, metadata
// defaults, structured-data (JSON-LD) builders and slug helpers.
// NOTHING here is fabricated: all opportunity-derived structured
// data is computed from real fields on the Opportunity object.

import type { Metadata } from 'next';
import type { Opportunity } from './gemini';

/**
 * Canonical origin. Configured via NEXT_PUBLIC_SITE_URL so the same
 * codebase works on preview, staging and the production domain
 * (opportunityos.dev) without hardcoding. No trailing slash.
 */
export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL || 'https://www.oppertunityos.dev'
).replace(/\/$/, '');

export const SITE_NAME = 'OpportunityOS AI';
export const SITE_TAGLINE = 'Your AI Chief Opportunity Officer';
export const TWITTER_HANDLE = '@opportunityos';

export const DEFAULT_DESCRIPTION =
  'OpportunityOS AI is the AI-powered Opportunity Operating System that helps students, researchers, founders and professionals discover and win scholarships, fellowships, grants, internships, hackathons, remote jobs and accelerators.';

/** Absolute URL for any path. */
export function absoluteUrl(path = ''): string {
  if (!path) return SITE_URL;
  return `${SITE_URL}${path.startsWith('/') ? path : `/${path}`}`;
}

/** URL-safe slug from arbitrary text (countries, categories, skills). */
export function toSlug(value: string): string {
  return value
    .toLowerCase()
    .trim()
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/** Default OG image path (generated by app/opengraph-image). */
export const OG_IMAGE = '/opengraph-image';

/**
 * Build a page Metadata object with sensible SEO defaults, canonical
 * URL and OpenGraph/Twitter cards. Pass a canonical `path` per page.
 */
export function buildMetadata(opts: {
  title: string;
  description: string;
  path: string;
  keywords?: string[];
  ogType?: 'website' | 'article';
  images?: string[];
  noindex?: boolean;
  publishedTime?: string;
}): Metadata {
  const url = absoluteUrl(opts.path);
  const images = opts.images?.length ? opts.images : [OG_IMAGE];
  return {
    title: opts.title,
    description: opts.description,
    keywords: opts.keywords,
    alternates: { canonical: url },
    openGraph: {
      title: opts.title,
      description: opts.description,
      url,
      siteName: SITE_NAME,
      locale: 'en_US',
      type: opts.ogType || 'website',
      images: images.map((u) => ({ url: u })),
      ...(opts.publishedTime ? { publishedTime: opts.publishedTime } : {}),
    },
    twitter: {
      card: 'summary_large_image',
      title: opts.title,
      description: opts.description,
      creator: TWITTER_HANDLE,
      images,
    },
    robots: opts.noindex
      ? { index: false, follow: false }
      : { index: true, follow: true },
  };
}

// ============================================================
//  JSON-LD structured data builders
// ============================================================

export function organizationJsonLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: SITE_NAME,
    url: SITE_URL,
    logo: absoluteUrl('/icon.svg'),
    description: DEFAULT_DESCRIPTION,
    sameAs: ['https://twitter.com/opportunityos'],
  };
}

export function websiteJsonLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: SITE_NAME,
    url: SITE_URL,
    description: DEFAULT_DESCRIPTION,
    potentialAction: {
      '@type': 'SearchAction',
      target: {
        '@type': 'EntryPoint',
        urlTemplate: `${SITE_URL}/opportunities?q={search_term_string}`,
      },
      'query-input': 'required name=search_term_string',
    },
  };
}

export function softwareApplicationJsonLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: SITE_NAME,
    applicationCategory: 'BusinessApplication',
    operatingSystem: 'Web',
    url: SITE_URL,
    description: DEFAULT_DESCRIPTION,
  };
}

export function breadcrumbJsonLd(items: { name: string; path: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: item.name,
      item: absoluteUrl(item.path),
    })),
  };
}

export function faqJsonLd(faqs: { question: string; answer: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map((f) => ({
      '@type': 'Question',
      name: f.question,
      acceptedAnswer: { '@type': 'Answer', text: f.answer },
    })),
  };
}

/**
 * Map an Opportunity to the most appropriate schema.org type using
 * ONLY real fields. Scholarships/Grants → EducationalOccupationalProgram
 * or Grant; Hackathons/Competitions → Event; Jobs → JobPosting.
 */
export function opportunityJsonLd(opp: Opportunity) {
  const url = absoluteUrl(`/opportunities/${opp.id}`);
  const type = String(opp.type).toLowerCase();
  const base: Record<string, unknown> = {
    '@context': 'https://schema.org',
    name: opp.title,
    description: opp.description,
    url,
    provider: {
      '@type': 'Organization',
      name: opp.provider,
      ...(opp.url ? { sameAs: opp.url } : {}),
    },
  };

  if (type.includes('job')) {
    return {
      ...base,
      '@type': 'JobPosting',
      title: opp.title,
      hiringOrganization: { '@type': 'Organization', name: opp.provider },
      ...(opp.remote ? { jobLocationType: 'TELECOMMUTE' } : {}),
      ...(opp.country
        ? { jobLocation: { '@type': 'Place', address: { '@type': 'PostalAddress', addressCountry: opp.country } } }
        : {}),
      ...(opp.deadline ? { validThrough: opp.deadline } : {}),
    };
  }

  if (type.includes('hackathon') || type.includes('competition') || type.includes('conference') || type.includes('event')) {
    return {
      ...base,
      '@type': 'Event',
      ...(opp.deadline ? { startDate: opp.deadline } : {}),
      eventAttendanceMode: opp.remote
        ? 'https://schema.org/OnlineEventAttendanceMode'
        : 'https://schema.org/OfflineEventAttendanceMode',
      location: opp.remote
        ? { '@type': 'VirtualLocation', url: opp.url || url }
        : { '@type': 'Place', name: opp.country },
      organizer: { '@type': 'Organization', name: opp.provider },
    };
  }

  // Default: scholarships, fellowships, grants, programs, research →
  // EducationalOccupationalProgram (Google's recommended type for these).
  return {
    ...base,
    '@type': 'EducationalOccupationalProgram',
    programType: String(opp.type),
    ...(opp.educationLevel?.length ? { educationalCredentialAwarded: opp.educationLevel.join(', ') } : {}),
    ...(opp.deadline ? { applicationDeadline: opp.deadline } : {}),
    ...(typeof opp.fundingAmount === 'number' && opp.fundingAmount > 0
      ? {
          offers: {
            '@type': 'Offer',
            price: opp.fundingAmount,
            priceCurrency: opp.currency || 'USD',
          },
        }
      : {}),
  };
}
